# The theme of the site
theme = "zola-academic"


# The title of the site
title = "Haoyu Li"

# The URL the site will be built for
base_url = "/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
#highlight_code = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[extra]
# Put all your custom variables here

# Author of the page
author = "Haoyu Li"

# Role of the author
role = "A Hacker & System Guy"

# Organizations of the author
organizations = [ { name = "Rutgers University-New Brunswick" } ]

# Whether the navbar should be screen wide or page wide
wide_navbar = false

# Url of your profile pic
# You should put your portrait in the static directory.
portrait = "/static/img/himmel-1-1.png"

# The links you want to put on the left of the navbar
menu_left = [
    # { name = "Blog", link = "https://0xdkxy.github.io/blog/"}
]

# The links you want to put on the right of the navbar
menu_right = [
    #{ name = "Projects", link = "/#projects" },
    { name = "Blog", link = "https://0xdkxy.github.io/blog/" },
    #{ name = "Posts", link = "/#posts" },
    #{ name = "Publications", link = "/#publications" },
    { name = "Contact", link = "/#contact" }
]

# Social icons that will appear under your profile box
social_icons = [
{icon="fa-envelope", icon_pack="fa", link="mailto:lowell@0xdkxy.com"},
#{icon="ai-google-scholar", icon_pack="ai", link="https://scholar.google.fr/"},
{icon="fa-github", icon_pack="fab", link="https://github.com/0xdkxy" },
]

# Your interests
# interests = [
#     { label = "Rust", link = "https://www.rust-lang.org/" },
#     { label = "Zola", link = "https://www.getzola.org/" },
#     { label = "Zola Academic", link = "https://github.com/zola-academic/zola-academic" }
# ]
interests = [
    { label = "Operating Systems" },
    { label = "Computer Architecture" }
]

# Your diplomas
education = [
#{course = "PhD in something", institution = "Somewhere, city, country", year = 2020},
{course = "Ph.D. in Computer Schience", institution = "Rutgers University-New Brunswick, NJ", year = "2024-Present"},
{course = "B.Eng in Computer Science and Technology", institution = "Central South University, Changsha, China", year = "2019-2023"},
]

# The ways people can contact you
contact_links = [
  {icon="fa-envelope", icon_pack="fa", name = "Email me", link="mailto:lowell@0xdkxy.com"},
  #{icon = "fa-twitter", icon_pack = "fab", name = "DM Me", link = "https://twitter.com/Twitter"},
  #{icon = "fa-skype", icon_pack = "fab", name = "Skype Me", link = "skype:echo123?call"},
  #{icon = "fa-keybase", icon_pack = "fab", name = "Chat on Keybase", link = "https://keybase.io/"},
  #{icon = "fa-comments", icon_pack = "fas", name = "Discuss on Forum", link = "https://zola.discourse.group/"},
  #{icon = "fa-discord", icon_pack = "fab", name = "John Doe #9999"},
]

# Disable the footer
disable_footer = false

# Widgets to show on main page
show_publications = false
show_posts = false
show_projects = false

# Choose your colorscheme among those
# colorscheme = "default"
colorscheme = "ocean"
# colorscheme = "forest"

